[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet = "3xHkGv5DngjJ3onZ54tXtjk35yZTXMxkukNq2WPcBGLj"
puppet-master = "FnZeJqZP3ArEmrJ1KdSkmer86PqFPumZS6JvDP17a15d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nhatminhphan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
